version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit_message:
      prefix: "chore"
      include_scope: true
    open-pull-requests-limit: 5
