name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '[0-9]+.x'
    tags:
      - '*'
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    name: Node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 16.x

      - name: Get Yarn Cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Yarn Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn2-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn2-

      - name: Deps
        run: |
          yarn --immutable

      - name: Info
        run: |
          node -v
          npm -v
          yarn -v
          yarn tsc -v

      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: |
          yarn lint
          yarn prettier:ci

      - name: Build
        run: |
          yarn build

      - name: Test
        run: |
          yarn test:ci

      - name: Browser Test
        working-directory: packages/drizzle-fetch
        run: |
          yarn test:e2e:prepare
          yarn test:e2e

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        id: setup-node
        uses: actions/setup-node@v3.1.0
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      - name: Get Yarn Cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Yarn Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn2-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn2-

      - name: Deps
        run: |
          yarn --immutable

      - name: Build
        run: |
          yarn build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn release:publish

      - name: Latest Changelog
        run: |
          diff --changed-group-format='%>' --unchanged-group-format='' <( git show HEAD~1:CHANGELOG.md ) CHANGELOG.md > CHANGELOG_LATEST.md || true

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG_LATEST.md
          draft: false
          prerelease: contains(github.ref, '-rc')
