name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - name: Cache Yarn
        uses: actions/cache@v2
        env:
          cache-name: cache-yarn
        with:
          path: ~/.yarn/berry/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Config Yarn
        run: |
          yarn set version berry
          yarn --version

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Build
        run: |
          yarn build:packages

      - name: Lint
        run: |
          yarn lint

      - name: Test
        run: |
          yarn test:ci
          yarn coverage:upload
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Build Release
        run: |
          yarn build:release
