name: ci

on:
  push:
    branches:
      - main
      - v[0-9]+.x-alpha
      - v[0-9]+.x
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

env:
  CI: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 12.x, 14.x ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Config Yarn
        run: |
          yarn set version berry
          yarn --version

      - name: Install dependencies
        run: |
          yarn

      - name: Lint
        run: |
          yarn lint

      - name: Test
        run: |
          node pkgs/drizzle-http-fetch/node_modules/puppeteer/install.js
          yarn test:ci
          yarn coverage:upload
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
