name: dependabot-yarn2-autofix

on:
  push:
    branches: [ dependabot/npm_and_yarn/** ]
  pull_request:
    branches: [ dependabot/npm_and_yarn/** ]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Deps Autofix
        run: |
          LAST_COMMIT=$(git log -1 --pretty=format:"%s")

          git checkout $(git log -n1 --skip 1 --oneline yarn.lock | awk '{print $1;}') -- yarn.lock

          PKG=$(yarn dependabot:utils pkg --title $LAST_COMMIT)
          FROM=$(yarn dependabot:utils from --title $LAST_COMMIT)
          TO=$(yarn dependabot:utils to --title $LAST_COMMIT)
          TYPE_AND_SCOPE=$(yarn dependabot:utils type-and-scope --title $LAST_COMMIT)

          yarn up $PKG $FROM@$^TO
          yarn

          git add yarn.lock package.json
          git commit -m "$TYPE_AND_SCOPE: fix bump $PKG from $FROM to $TO"
          git push
